replicaCount: 1

indexHtml: |
  <!DOCTYPE html>
  <html lang="en">
  <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Welcome to Nginx</title>
  </head>
  <body>
      <h1>Welcome to Nginx!</h1>
      <p>This is a new static page from custom-values.yaml.</p>
      <p>Pod Name: POD_NAME</p>
  </body>
  </html>

