apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app | default "nginx" }}
  strategy:
    type: {{ .Values.Deployment.strategyType }}
    rollingUpdate:
      maxSurge: {{ .Values.Deployment.maxSurge }}
      maxUnavailable: {{ .Values.Deployment.maxUnavailable }}
  template:
    metadata:
      annotations:
        helm.sh/revision: "{{ .Release.Revision }}"
      labels:
        app: {{ .Values.labels.app | default "nginx" }}
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: app-nginx
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: app-nginx
      containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          volumeMounts:
            - name: {{ .Release.Name }}-server-block-config
              mountPath: /etc/nginx/templates/default.conf.template
              subPath: default.conf.template
            - name: {{ .Release.Name }}-index-config
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - name: {{ .Values.ports.name }}
              containerPort: {{ .Values.ports.containerPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            #securityContext:
              #privileged: false
              #allowPrivilegeEscalation: false
              #runAsUser: 101
      volumes:
        - name: {{ .Release.Name }}-server-block-config
          configMap:
            name: {{ .Release.Name }}-server-block-config
        - name: {{ .Release.Name }}-index-config
          configMap:
            name: {{ .Release.Name }}-index-config

