apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.HorizontalPodAutoscaler.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.HorizontalPodAutoscaler.nameTarget }}
  minReplicas: {{ .Values.HorizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.HorizontalPodAutoscaler.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.HorizontalPodAutoscaler.targetCPUUtilizationPercentage }}

