apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-index-config
data:
  {{- if .Values.indexHtml }}
  index.html: |
    {{ .Values.indexHtml | nindent 4 }}
  {{- else }}
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Welcome to Nginx</title>
    </head>
    <body>
        <h1>Welcome to Nginx!</h1>
        <p>If you see this page, the Nginx web server is successfully configured from Helm-chart {{ .Chart.Name }}, version: {{ .Chart.Version }}.</p>
        <p>Learn more about deploying and managing applications with Kubernetes in our comprehensive Kubernetes course.</p>
        <p>Pod Name: POD_NAME</p>
    </body>
    </html>
  {{- end }}

